import { Archetype } from "./types";

export const ARCHETYPES: Archetype[] = [
  {
    key: "burnt_out",
    name: "The Burnt-Out Professional",
    description: "High-achiever drowning in deadlines, surviving on delivery apps and caffeine.",
    wellnessBaseline: 55,
    traits: ["Works 50+ hours/week", "Skips meals or stress-eats", "High screen time", "Poor sleep quality"],
    triggerPoints: ["Late-night DoorDash orders", "Skipping the gym", "Energy drink purchases"],
    avatarColor: "#F59E0B",
    avatarBg: "from-amber-100 to-orange-100",
  },
  {
    key: "former_athlete",
    name: "The Former Athlete",
    description: "Once fit, now struggling as metabolism slows and old habits don't work.",
    wellnessBaseline: 65,
    traits: ["Used to be very active", "Eating same portions but moving less", "Nostalgic about past fitness", "Prone to injuries"],
    triggerPoints: ["Large portion sizes", "Beer and sports drinks", "Skipping recovery days"],
    avatarColor: "#84CC16",
    avatarBg: "from-lime-100 to-green-100",
  },
  {
    key: "overwhelmed_parent",
    name: "The Overwhelmed Parent",
    description: "Putting everyone else first, grabbing whatever food is fast and easy.",
    wellnessBaseline: 50,
    traits: ["Zero personal time", "Eats kids' leftovers", "Exhausted constantly", "Feels guilty about self-care"],
    triggerPoints: ["Drive-thru runs", "Snacking after kids sleep", "Skipping workouts for family"],
    avatarColor: "#F472B6",
    avatarBg: "from-rose-100 to-pink-100",
  },
  {
    key: "social_butterfly",
    name: "The Social Butterfly",
    description: "Life revolves around events, dinners, and drinks with friends.",
    wellnessBaseline: 60,
    traits: ["Multiple social events weekly", "FOMO drives decisions", "Vulnerable to peer pressure", "Weekend warrior mentality"],
    triggerPoints: ["Group food orders", "Happy hour invitations", "Brunches", "Peer pressure moments"],
    avatarColor: "#FACC15",
    avatarBg: "from-yellow-100 to-amber-100",
  },
  {
    key: "night_owl",
    name: "The Night Owl",
    description: "Comes alive after dark, makes worst decisions between 10pm-2am.",
    wellnessBaseline: 58,
    traits: ["Reversed sleep schedule", "Late-night snacker", "Peak productivity at night", "Mornings are the enemy"],
    triggerPoints: ["Midnight cravings", "Endless scrolling sessions", "Late gaming sessions"],
    avatarColor: "#6366F1",
    avatarBg: "from-indigo-100 to-violet-100",
  },
  {
    key: "emotional_eater",
    name: "The Emotional Eater",
    description: "Food is comfort, reward, and coping mechanism all in one.",
    wellnessBaseline: 52,
    traits: ["Eats feelings", "Reward = food", "Stress = snacks", "Cycles of guilt"],
    triggerPoints: ["Bad day comfort food", "Celebration meals", "Boredom eating"],
    avatarColor: "#FB923C",
    avatarBg: "from-peach-100 to-orange-100",
  },
  {
    key: "serial_starter",
    name: "The Serial Starter",
    description: "Has tried every diet, app, and program. Starts strong, fades fast.",
    wellnessBaseline: 55,
    traits: ["Graveyard of diet apps", "Unused gym memberships", "High initial enthusiasm", "Quick to abandon"],
    triggerPoints: ["'Last meal before the diet' binges", "Endless research on new programs", "Equipment purchases"],
    avatarColor: "#F97316",
    avatarBg: "from-orange-100 to-amber-100",
  },
  {
    key: "mindless_grazer",
    name: "The Mindless Grazer",
    description: "Doesn't overeat at meals but constantly nibbles throughout the day.",
    wellnessBaseline: 57,
    traits: ["Never feels truly full", "Always snacking", "Loses track of intake", "Eats out of boredom"],
    triggerPoints: ["Frequent pantry visits", "Eating while cooking", "TV snacking", "Desk snacking"],
    avatarColor: "#9CA3AF",
    avatarBg: "from-gray-100 to-slate-100",
  },
  {
    key: "perfectionist_quitter",
    name: "The Perfectionist Quitter",
    description: "One slip-up ruins everything. All or nothing mentality.",
    wellnessBaseline: 53,
    traits: ["Rigid rules about food/exercise", "Binary thinking", "Extremely self-critical", "'Restart Monday' mentality"],
    triggerPoints: ["'Ruined day' binges", "Post-slip spirals", "Avoiding tracking after mistakes"],
    avatarColor: "#64748B",
    avatarBg: "from-slate-100 to-gray-200",
  },
  {
    key: "mindful_aspirant",
    name: "The Mindful Aspirant",
    description: "Already on the journey, needs tools to stay consistent and go deeper.",
    wellnessBaseline: 70,
    traits: ["Health-conscious already", "Seeks balance", "Self-aware", "Ready to level up"],
    triggerPoints: ["Travel disruptions", "Busy work periods", "Challenging social situations"],
    avatarColor: "#14B8A6",
    avatarBg: "from-teal-100 to-emerald-100",
  },
];

export function getArchetype(key: string) {
  return ARCHETYPES.find((a) => a.key === key) || ARCHETYPES[9];
}
