import { Question } from "./types";

export const QUESTIONS: Question[] = [
  // Section 1: Who Were You?
  {
    id: "Q1",
    section: 1,
    sectionTitle: "Who Were You?",
    text: "Think back to a time \u2014 maybe university, maybe earlier \u2014 when you felt most like yourself. What did a typical morning look like?",
    type: "open_text",
    placeholder: "Describe your morning routine from that time...",
    maxLength: 500,
  },
  {
    id: "Q2",
    section: 1,
    sectionTitle: "Who Were You?",
    text: "When you had free time back then, what did you actually do with it \u2014 not what you thought you should do, but what you genuinely chose?",
    type: "open_text",
    placeholder: "What did you genuinely choose to do...",
    maxLength: 500,
  },
  {
    id: "Q3",
    section: 1,
    sectionTitle: "Who Were You?",
    text: "Which of these best describes how you used to recharge?",
    type: "choice",
    options: [
      { key: "A", label: "Moving my body \u2014 a run, a sport, a long walk" },
      { key: "B", label: "Being around people who energized me" },
      { key: "C", label: "Quiet and stillness \u2014 alone time, reading, music" },
      { key: "D", label: "Creating or building something" },
      { key: "E", label: "A mix of all of these" },
    ],
  },
  {
    id: "Q4",
    section: 1,
    sectionTitle: "Who Were You?",
    text: "When you were at your most consistent, what did that feel like from the inside?",
    type: "choice",
    options: [
      { key: "A", label: "Effortless \u2014 it just happened" },
      { key: "B", label: "Disciplined \u2014 I worked for it" },
      { key: "C", label: "Social \u2014 others kept me going" },
      { key: "D", label: "Environmental \u2014 the structure was just there" },
    ],
  },
  {
    id: "Q5",
    section: 1,
    sectionTitle: "Who Were You?",
    text: "What\u2019s something you did regularly back then that you\u2019ve quietly stopped \u2014 that you haven\u2019t really told anyone about?",
    type: "open_text",
    placeholder: "Something you quietly stopped doing...",
    maxLength: 500,
  },
  {
    id: "Q6",
    section: 1,
    sectionTitle: "Who Were You?",
    text: "Back then, what was the thing you were most protective of \u2014 the part of your day or routine you wouldn\u2019t let anything touch?",
    type: "open_text",
    placeholder: "The part of your routine you protected...",
    maxLength: 500,
  },
  // Section 2: Who Are You Today?
  {
    id: "Q7",
    section: 2,
    sectionTitle: "Who Are You Today?",
    text: "Your life has shifted. When you think about your average Tuesday now, what\u2019s the first feeling that comes up?",
    type: "choice",
    options: [
      { key: "A", label: "Busy but okay" },
      { key: "B", label: "Productive but hollow" },
      { key: "C", label: "Tired in a way sleep doesn\u2019t fix" },
      { key: "D", label: "Honestly, a bit lost" },
      { key: "E", label: "Fine \u2014 things are different but I\u2019m adapting" },
    ],
  },
  {
    id: "Q8",
    section: 2,
    sectionTitle: "Who Are You Today?",
    text: "How much of your identity right now is tied to your job or career?",
    type: "slider",
    sliderMin: 0,
    sliderMax: 100,
    sliderMinLabel: "None of it",
    sliderMaxLabel: "Almost all of it",
  },
  {
    id: "Q9",
    section: 2,
    sectionTitle: "Who Are You Today?",
    text: "When was the last time you did something purely because it felt good \u2014 not because it was productive, healthy, or impressive?",
    type: "choice",
    options: [
      { key: "A", label: "This week" },
      { key: "B", label: "This month" },
      { key: "C", label: "I honestly can\u2019t remember" },
      { key: "D", label: "I\u2019m not sure I let myself do that anymore" },
    ],
  },
  {
    id: "Q10",
    section: 2,
    sectionTitle: "Who Are You Today?",
    text: "What\u2019s the first thing you reach for when you\u2019re stressed, tired, or bored?",
    type: "open_text",
    placeholder: "What do you reach for...",
    maxLength: 300,
  },
  {
    id: "Q11",
    section: 2,
    sectionTitle: "Who Are You Today?",
    text: "Which of these patterns do you recognize in yourself right now?",
    type: "multi_select",
    options: [
      { key: "busier", label: "I\u2019m busier than ever but feel less like myself" },
      { key: "know_but_dont", label: "I know what I should do \u2014 I just don\u2019t do it" },
      { key: "stopped_loving", label: "I\u2019ve stopped doing things I used to love without really deciding to" },
      { key: "phone_check", label: "I check my phone more than I\u2019d like to admit" },
      { key: "performing", label: "I feel like I\u2019m performing a version of myself rather than being it" },
      { key: "night_different", label: "I eat, spend, or scroll differently at night than I intend to during the day" },
    ],
  },
  {
    id: "Q12",
    section: 2,
    sectionTitle: "Who Are You Today?",
    text: "What time of day do you feel most like yourself right now?",
    type: "choice",
    options: [
      { key: "A", label: "Morning" },
      { key: "B", label: "Afternoon" },
      { key: "C", label: "Evening" },
      { key: "D", label: "Honestly, rarely" },
    ],
  },
  {
    id: "Q13",
    section: 2,
    sectionTitle: "Who Are You Today?",
    text: "Is there a version of yourself \u2014 even a small piece \u2014 that you miss?",
    type: "open_text",
    placeholder: "A version of yourself you miss...",
    maxLength: 500,
  },
  {
    id: "Q14",
    section: 2,
    sectionTitle: "Who Are You Today?",
    text: "What\u2019s one thing that\u2019s genuinely different about your life now that makes the old routines hard to maintain?",
    type: "open_text",
    placeholder: "What\u2019s different now...",
    maxLength: 500,
  },
  // Section 3: Eating & Behavioral Patterns
  {
    id: "Q15",
    section: 3,
    sectionTitle: "Eating & Behavioral Patterns",
    text: "Which BEST describes your eating pattern?",
    type: "choice",
    options: [
      { key: "A", label: "I graze constantly \u2014 always nibbling on something" },
      { key: "B", label: "I skip meals then overeat later \u2014 feast or famine" },
      { key: "C", label: "My eating revolves around social situations" },
      { key: "D", label: "I eat emotionally \u2014 stress, boredom, sadness, even joy" },
      { key: "E", label: "I eat whatever\u2019s fastest \u2014 cooking feels impossible" },
      { key: "F", label: "Fairly regular meals with occasional indulgences" },
    ],
  },
  {
    id: "Q16",
    section: 3,
    sectionTitle: "Eating & Behavioral Patterns",
    text: "What\u2019s your relationship with food delivery apps?",
    type: "choice",
    options: [
      { key: "A", label: "Daily habit \u2014 it\u2019s my default for most meals" },
      { key: "B", label: "Stress response \u2014 I order when exhausted or emotional" },
      { key: "C", label: "Social \u2014 I order when others want to" },
      { key: "D", label: "Mostly weekends \u2014 when my structure falls apart" },
      { key: "E", label: "Occasional \u2014 maybe 1\u20132x per week" },
      { key: "F", label: "Rarely use them" },
    ],
  },
  {
    id: "Q17",
    section: 3,
    sectionTitle: "Eating & Behavioral Patterns",
    text: "When you eat something you regret, what happens next?",
    type: "choice",
    options: [
      { key: "A", label: "I spiral \u2014 \u201calready ruined it, might as well continue\u201d" },
      { key: "B", label: "I feel guilty and eat more to cope" },
      { key: "C", label: "I try to compensate \u2014 skip meals, exercise extra" },
      { key: "D", label: "I don\u2019t really notice \u2014 it all blurs together" },
      { key: "E", label: "I shrug and make my next choice fresh" },
    ],
  },
  {
    id: "Q18",
    section: 3,
    sectionTitle: "Eating & Behavioral Patterns",
    text: "What\u2019s your pattern with \u201cstarting fresh\u201d?",
    type: "choice",
    options: [
      { key: "A", label: "Graveyard of Day 1s \u2014 new plans that never stick" },
      { key: "B", label: "Great until one slip, then I abandon everything" },
      { key: "C", label: "I avoid committing \u2014 never really tried fully" },
      { key: "D", label: "I do well until life disrupts me" },
      { key: "E", label: "I\u2019ve built some lasting habits, even if imperfect" },
    ],
  },
  {
    id: "Q19",
    section: 3,
    sectionTitle: "Eating & Behavioral Patterns",
    text: "What does your typical evening look like?",
    type: "choice",
    options: [
      { key: "A", label: "Collapse \u2014 I just want delivery and screens" },
      { key: "B", label: "Second shift \u2014 more responsibilities, then collapse" },
      { key: "C", label: "Often social \u2014 dinner plans, catching up with people" },
      { key: "D", label: "Night mode \u2014 I finally have me-time, so I stay up late" },
      { key: "E", label: "Unstructured \u2014 floating between snacking and scrolling" },
      { key: "F", label: "Fairly consistent \u2014 I have routines that work" },
    ],
  },
  // Section 4: Mental State & Triggers
  {
    id: "Q20",
    section: 4,
    sectionTitle: "Mental State & Triggers",
    text: "Which thinking pattern fits you MOST?",
    type: "choice",
    options: [
      { key: "A", label: "All-or-nothing \u2014 perfect or complete failure, no middle" },
      { key: "B", label: "Excited starter \u2014 fired up at first, lose steam in weeks" },
      { key: "C", label: "Low awareness \u2014 don\u2019t notice patterns until consequences hit" },
      { key: "D", label: "Emotion-driven \u2014 feelings control choices, logic doesn\u2019t help" },
      { key: "E", label: "Externally-focused \u2014 I adapt to whoever I\u2019m around" },
      { key: "F", label: "Self-aware \u2014 I see my patterns, just need better systems" },
    ],
  },
  {
    id: "Q21",
    section: 4,
    sectionTitle: "Mental State & Triggers",
    text: "What MOST triggers your unhealthy choices?",
    type: "choice",
    options: [
      { key: "A", label: "Stress or exhaustion \u2014 willpower gone" },
      { key: "B", label: "Boredom or emptiness \u2014 need stimulation" },
      { key: "C", label: "Social situations \u2014 I match what others do" },
      { key: "D", label: "Late night \u2014 I fall apart after 9pm" },
      { key: "E", label: "Emotions \u2014 specific feelings drive me to food" },
      { key: "F", label: "Environment \u2014 certain places trigger me" },
    ],
  },
  {
    id: "Q22",
    section: 4,
    sectionTitle: "Mental State & Triggers",
    text: "When are you MOST likely to make a choice you\u2019ll regret?",
    type: "choice",
    options: [
      { key: "A", label: "Late night (after 9pm)" },
      { key: "B", label: "Afternoon slump (2\u20135pm)" },
      { key: "C", label: "Weekends \u2014 structure disappears" },
      { key: "D", label: "After a setback \u2014 one mistake leads to \u201cmight as well\u201d" },
      { key: "E", label: "Social settings \u2014 can\u2019t resist when others indulge" },
      { key: "F", label: "When emotions hit \u2014 stress, sadness, even celebration" },
    ],
  },
  {
    id: "Q23",
    section: 4,
    sectionTitle: "Mental State & Triggers",
    text: "What would ACTUALLY make you stop at a trigger moment?",
    type: "choice",
    options: [
      { key: "A", label: "Hard data \u2014 \u201c5th order this week, $127 spent\u201d" },
      { key: "B", label: "Future reflection \u2014 \u201cHow will you feel tomorrow?\u201d" },
      { key: "C", label: "Direct challenge \u2014 \u201cYou said you wanted to change\u201d" },
      { key: "D", label: "Gentle check-in \u2014 \u201cWhat\u2019s actually going on right now?\u201d" },
      { key: "E", label: "Better alternative \u2014 \u201cTry this instead, you\u2019ll feel great\u201d" },
      { key: "F", label: "My avatar looking at me \u2014 visual accountability" },
    ],
  },
  // Section 5: Motivation & Goals
  {
    id: "Q24",
    section: 5,
    sectionTitle: "Motivation & Goals",
    text: "What\u2019s your PRIMARY motivation for wanting to change?",
    type: "choice",
    options: [
      { key: "A", label: "Energy \u2014 I want to feel alive again" },
      { key: "B", label: "Control \u2014 I want to make conscious choices" },
      { key: "C", label: "Appearance \u2014 I want to look and feel better" },
      { key: "D", label: "Peace \u2014 I want freedom from guilt and food stress" },
      { key: "E", label: "Consistency \u2014 I want something that finally sticks" },
      { key: "F", label: "Balance \u2014 enjoy life AND take care of myself" },
    ],
  },
  {
    id: "Q25",
    section: 5,
    sectionTitle: "Motivation & Goals",
    text: "What has ACTUALLY stopped you from changing before?",
    type: "choice",
    options: [
      { key: "A", label: "One slip became a landslide \u2014 couldn\u2019t recover" },
      { key: "B", label: "Motivation faded \u2014 started strong, couldn\u2019t maintain" },
      { key: "C", label: "Life disrupted \u2014 any change threw me off" },
      { key: "D", label: "Social pressure \u2014 couldn\u2019t stay on track around others" },
      { key: "E", label: "No quick results \u2014 got discouraged and quit" },
      { key: "F", label: "Fear of failure \u2014 scared to fully commit and fail" },
      { key: "G", label: "Still working on it \u2014 made progress, want more tools" },
    ],
  },
];

export const SECTION_TITLES = [
  "Who Were You?",
  "Who Are You Today?",
  "Eating & Behavioral Patterns",
  "Mental State & Triggers",
  "Motivation & Goals",
];
